language: python

matrix:
    fast_finish: true
    include:
        - python: "2.7"
          env: TOX_ENV=py27-django18
        - python: "2.7"
          env: TOX_ENV=py27-django19
        - python: "2.7"
          env: TOX_ENV=py27-django110
        - python: "2.7"
          env: TOX_ENV=py27-django111

        - python: "3.4"
          env: TOX_ENV=py34-django18
        - python: "3.4"
          env: TOX_ENV=py34-django19
        - python: "3.4"
          env: TOX_ENV=py34-django110
        - python: "3.4"
          env: TOX_ENV=py34-django111

        - python: "3.5"
          env: TOX_ENV=py35-django18
        - python: "3.5"
          env: TOX_ENV=py35-django19
        - python: "3.5"
          env: TOX_ENV=py35-django110
        - python: "3.5"
          env: TOX_ENV=py35-django111
        - python: "3.5"
          env: TOX_ENV=py35-django20
        - python: "3.5"
          env: TOX_ENV=py35-django21

        - python: "3.6"
          env: TOX_ENV=py36-django20
        - python: "3.6"
          env: TOX_ENV=py36-django21

addons:
    postgesql: "9.3"

services:
    - postgresql

before_install:
    - pip install codecov

install:
    - pip install tox

before_script:
    - psql -c 'create database migrate_sql_test_db;' -U postgres

script:
    - tox -e $TOX_ENV

after_success:
    - codecov -e TOX_ENV
